# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll"
gem "jekyll-theme-slate"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

gem "github-pages", "~> 206", group: :jekyll_plugins

#group :jekyll_plugins do
#  gem "jekyll-feed"
#  gem "jykell-seo-tag"
#end
